### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by backender** [kollektiv-hackathon/zmittapp-web#2]
Get an API key.

![screen shot 2014-12-21 at 16 29 05](https://cloud.githubusercontent.com/assets/955179/5518575/8fa70472-892e-11e4-8481-e0ac1cdfc5c7.png)

**Comment by backender** [comment]
306a6087daf5883367a4a8f3a7c42c089b8983af

**Comment by remolueoend** [comment]
Are you running the local App under http://localhost? The original API key was created for http://zmittapp.int.

**Comment by backender** [comment]
running virtualhost under http://zmittapp.web/ 
aren't those keys ip specific? -> i just allowed all ip's for the current key.

**Comment by remolueoend** [comment]
If it is IP specific and it works, lets close this issue ;)
